#!/usr/bin/env node
/**
 * ibitlabs-mcp server
 *
 * Public read access to the iBitLabs $1k → $10k AI trading experiment.
 * Tools return real account balance, real fills, the contributor ledger
 * of adopted shadow rules, and saga chapters. All data sourced from
 * www.ibitlabs.com — no credentials needed.
 *
 * All 5 tools wired to live public endpoints:
 *   GET  https://www.ibitlabs.com/api/live-status
 *   GET  https://www.ibitlabs.com/data/contributors.json
 *   GET  https://www.ibitlabs.com/data/saga_vol2.json
 *   GET  https://www.ibitlabs.com/data/recent_trades.json    (generated by scripts/export_mcp_data.py)
 *   GET  https://www.ibitlabs.com/data/rule_status.json      (generated by scripts/export_mcp_data.py)
 *
 * Repo: https://github.com/bbismm/ibitlabs (MIT)
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const BASE = "https://www.ibitlabs.com";
const LIVE_STATUS    = `${BASE}/api/live-status`;
const CONTRIBUTORS   = `${BASE}/data/contributors.json`;
const SAGA_VOL2      = `${BASE}/data/saga_vol2.json`;
const RECENT_TRADES  = `${BASE}/data/recent_trades.json`;
const RULE_STATUS    = `${BASE}/data/rule_status.json`;

// ─── Tool definitions ────────────────────────────────────────────────

const TOOLS = [
  {
    name: "get_live_status",
    description:
      "Current account snapshot from the live $1k → $10k experiment: balance, total/unrealized PnL, win rate, fees, funding cost, current open position (if any), reconciliation timestamp. Sourced from /api/live-status. Use when you need the actual current state of the bot instead of a backtest figure.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "get_recent_trades",
    description:
      "List the most recent N closed trades with entry/exit/PnL/regime tags. Use this to cite real fills (e.g. for a research post or an example in a strategy doc). Sourced from /data/recent_trades.json, regenerated after each morning/evening sniper check.",
    inputSchema: {
      type: "object",
      properties: {
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          default: 10,
          description: "Number of recent closed trades to return (1-100).",
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "list_adopted_rules",
    description:
      "List all contributor-proposed shadow rules: adopted (in production observation-only mode, with 30-day promotion windows) and queued_for_review (proposed but not yet wired). Each row carries proposer handle, frame, source post URL, rule_id, code_location, shadow_log path, review window, and current points. Sourced from /data/contributors.json. Use to see who has contributed encodable frames to the bot.",
    inputSchema: {
      type: "object",
      properties: {
        status: {
          type: "string",
          enum: ["adopted", "queued", "all"],
          default: "all",
          description: "Filter by review_status. Default is `all`.",
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_rule_status",
    description:
      "Per-rule shadow log statistics: number of fires, per-bucket hit rates, distance from the 4-condition promotion bar (≥30/bucket, ≥15pp spread, direction match, no confounding shadow). Use when reviewing whether a contributor's rule is on track to graduate from log-only shadow to a real entry gate. Sourced from /data/rule_status.json, regenerated after each morning/evening sniper check.",
    inputSchema: {
      type: "object",
      properties: {
        rule_id: {
          type: "string",
          description: "Single uppercase letter rule id (e.g. 'C', 'D', 'E', 'F', 'G').",
          pattern: "^[A-Z]$",
        },
      },
      required: ["rule_id"],
      additionalProperties: false,
    },
  },
  {
    name: "get_latest_saga_chapter",
    description:
      "Latest saga chapter narrating the experiment in human prose — pulls from /data/saga_vol2.json and returns the entry for the requested language. Use when you want a human-readable summary of the most recent state, not just numbers. The saga is updated daily (or near-daily) and pairs with the trading data above.",
    inputSchema: {
      type: "object",
      properties: {
        lang: {
          type: "string",
          enum: ["en", "zh"],
          default: "en",
          description: "Saga language. Default `en`.",
        },
      },
      additionalProperties: false,
    },
  },
];

// ─── Tool handlers ───────────────────────────────────────────────────

async function fetchJson<T = unknown>(url: string): Promise<T> {
  const res = await fetch(url, { headers: { Accept: "application/json" } });
  if (!res.ok) {
    throw new Error(`Upstream ${res.status} on ${url}`);
  }
  return (await res.json()) as T;
}

async function handleGetLiveStatus() {
  const data = await fetchJson<Record<string, unknown>>(LIVE_STATUS);
  // Strip noisy/internal fields, keep what an external caller cares about.
  const surfaced = {
    ts: data.ts,
    alive: data.alive,
    mode: data.mode,
    balance: data.balance,
    starting_capital: data.starting_capital,
    total_pnl: data.total_pnl,
    unrealized_pnl: data.unrealized_pnl,
    daily_pnl: data.daily_pnl,
    total_fees: data.total_fees,
    funding_cost: data.funding_cost,
    total_trades: data.total_trades,
    total_wins: data.total_wins,
    total_losses: data.total_losses,
    win_rate: data.win_rate,
    long_trades: data.long_trades,
    short_trades: data.short_trades,
    regime: data.regime,
    regime_detail: data.regime_detail,
    cooldown_remaining: data.cooldown_remaining,
    position: data.position,
    reconciliation: data.reconciliation,
  };
  return surfaced;
}

interface RecentTradesDoc {
  generated_at: string;
  count: number;
  slice_win_rate: number | null;
  trades: Array<Record<string, unknown>>;
}

async function handleGetRecentTrades(args: { limit?: number }) {
  const limit = Math.min(args.limit ?? 10, 100);
  const data = await fetchJson<RecentTradesDoc>(RECENT_TRADES);
  return {
    generated_at: data.generated_at,
    requested: limit,
    returned: Math.min(limit, data.trades.length),
    slice_win_rate: data.slice_win_rate,
    trades: data.trades.slice(0, limit),
  };
}

interface ContributorsDoc {
  schema_version: number;
  last_updated: string;
  page_intent: string;
  points_legend: unknown;
  adopted: Array<Record<string, unknown>>;
  queued_for_review: Array<Record<string, unknown>>;
}

async function handleListAdoptedRules(args: { status?: "adopted" | "queued" | "all" }) {
  const status = args.status ?? "all";
  const data = await fetchJson<ContributorsDoc>(CONTRIBUTORS);

  const adopted = data.adopted ?? [];
  const queued = data.queued_for_review ?? [];

  const out: Record<string, unknown> = {
    last_updated: data.last_updated,
    counts: { adopted: adopted.length, queued: queued.length },
  };
  if (status === "adopted" || status === "all") out.adopted = adopted;
  if (status === "queued" || status === "all") out.queued_for_review = queued;
  return out;
}

interface RuleStatusDoc {
  generated_at: string;
  rules: Record<string, Record<string, unknown>>;
}

async function handleGetRuleStatus(args: { rule_id: string }) {
  const data = await fetchJson<RuleStatusDoc>(RULE_STATUS);
  const rule = data.rules[args.rule_id];
  if (!rule) {
    const available = Object.keys(data.rules).join(", ");
    return {
      error: "rule_not_found",
      requested: args.rule_id,
      available_rule_ids: available,
    };
  }
  return { generated_at: data.generated_at, ...rule };
}

interface SagaDoc {
  updated: string;
  vol2_starts: string;
  entries: Array<{
    date: string;
    dayNumber: number;
    lang: "en" | "zh";
    title: string;
    preview: string;
    url: string;
  }>;
}

async function handleGetLatestSagaChapter(args: { lang?: "en" | "zh" }) {
  const lang = args.lang ?? "en";
  // saga_vol2.json sometimes contains unescaped quotes inside `preview` strings,
  // which breaks strict JSON parsing. Fetch as text, then attempt parse with a
  // best-effort fallback that surfaces the raw content if the index is malformed.
  const res = await fetch(SAGA_VOL2);
  if (!res.ok) throw new Error(`Upstream ${res.status} on ${SAGA_VOL2}`);
  const text = await res.text();
  let data: SagaDoc;
  try {
    data = JSON.parse(text) as SagaDoc;
  } catch (err) {
    return {
      error: "saga_index_malformed",
      detail: (err as Error).message,
      hint: "saga_vol2.json contains unescaped quotes; index needs sanitizing in the CMS pipeline.",
    };
  }

  const entries = (data.entries ?? []).filter((e) => e.lang === lang);
  if (entries.length === 0) {
    return { error: "no_entries_for_lang", lang };
  }
  // Already sorted newest-first in production, but don't trust it.
  entries.sort((a, b) => (a.date < b.date ? 1 : -1));
  const latest = entries[0];

  return {
    saga_updated: data.updated,
    vol2_starts: data.vol2_starts,
    chapter: {
      ...latest,
      full_url: `${BASE}${latest.url}`,
    },
  };
}

// ─── MCP wiring ──────────────────────────────────────────────────────

const server = new Server(
  { name: "ibitlabs-mcp", version: "0.1.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params;
  try {
    let result: unknown;
    switch (name) {
      case "get_live_status":
        result = await handleGetLiveStatus();
        break;
      case "get_recent_trades":
        result = await handleGetRecentTrades(args as { limit?: number });
        break;
      case "list_adopted_rules":
        result = await handleListAdoptedRules(
          args as { status?: "adopted" | "queued" | "all" },
        );
        break;
      case "get_rule_status":
        result = await handleGetRuleStatus(args as { rule_id: string });
        break;
      case "get_latest_saga_chapter":
        result = await handleGetLatestSagaChapter(args as { lang?: "en" | "zh" });
        break;
      default:
        throw new Error(`Unknown tool: ${name}`);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
    };
  } catch (err) {
    return {
      isError: true,
      content: [
        {
          type: "text",
          text: JSON.stringify({ error: (err as Error).message }, null, 2),
        },
      ],
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
