#!/usr/bin/env python3
from __future__ import annotations
"""
iBitLabs — Daily Trade Report Auto-Generator (v2)
===================================================
Reads ACTUAL data from:
  1. reports/YYYY-MM-DD.json (daily report files from daily_report.py)
  2. sol_sniper.db → trade_log table (fallback)

Generates:
  - Branded P&L chart (PNG)
  - Telegram Channel message (@ibitlabs_sniper)
  - Ready-to-paste Twitter copy

Setup:
  pip3 install matplotlib requests
  Place in ~/ibitlabs/scripts/
  LaunchAgent: com.ibitlabs.daily-report-v2 (daily 00:05 UTC)

Usage:
  python3 daily_report_generator.py [--date 2026-04-07] [--dry-run]
"""

import os
import sys
import json
import sqlite3
import argparse
import requests
from datetime import datetime, timedelta, timezone
from pathlib import Path

# ---------- CONFIG ----------
BASE_DIR = Path(__file__).parent.parent  # ~/ibitlabs
REPORT_DIR = BASE_DIR / "reports"
DB_PATH = BASE_DIR / "sol_sniper.db"
OUTPUT_DIR = BASE_DIR / "reports"  # reuse existing reports dir

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHANNEL_ID = os.getenv("TELEGRAM_CHANNEL_ID", "@ibitlabs_sniper")

# Social pared back 2026-04-22 → 2026-04-30. Telegram stays on (own channel).
# Twitter post path is gated; drafts still save to disk.
# Set TWITTER_ENABLED=1 in env to re-enable without touching code.
TWITTER_ENABLED = os.getenv("TWITTER_ENABLED", "0") == "1"

STARTING_CAPITAL = 1000.0
WEBSITE_URL = "https://ibitlabs.com"
SIGNALS_URL = "https://ibitlabs.com/signals"
SAGA_URL = "https://ibitlabs.com/saga/en"
LIVE_STATUS_URL = "https://ibitlabs.com/api/live-status"


# ---------- DATA LOADING ----------

def fetch_live_status(timeout: int = 10) -> dict | None:
    """
    Fetch authoritative balance + cumulative PnL + fees + funding from the live
    API. This is the source of truth; DB-only computation undercounts by missing
    fees ($30+ cumulative), funding ($27+ cumulative), and prior-days realized
    PnL (had been silently resetting balance to $1000 + today_pnl_only).

    Added 2026-04-23 to fix Telegram daily-report balance bug where the report
    showed $1,016.92 Balance while actual was $975-$979 (a $40+ misstatement).

    Returns None on network failure. Callers should handle None gracefully.
    """
    try:
        resp = requests.get(LIVE_STATUS_URL, timeout=timeout)
        resp.raise_for_status()
        data = resp.json()
        return data
    except Exception as e:
        print(f"⚠️  live-status fetch failed: {e} — falling back to DB-only")
        return None


def load_report_json(target_date: str):
    """Load the daily report JSON generated by daily_report.py."""
    report_file = REPORT_DIR / f"{target_date}.json"
    if report_file.exists():
        with open(report_file, "r") as f:
            return json.load(f)
    return None


def load_trades_from_db(target_date: str) -> list[dict]:
    """Fallback: load trades from sol_sniper.db trade_log for a given date."""
    if not DB_PATH.exists():
        return []

    # Parse date range as timestamps
    dt_start = datetime.strptime(target_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    dt_end = dt_start + timedelta(days=1)
    ts_start = dt_start.timestamp()
    ts_end = dt_end.timestamp()

    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    rows = db.execute(
        "SELECT * FROM trade_log WHERE timestamp >= ? AND timestamp < ? ORDER BY timestamp",
        (ts_start, ts_end)
    ).fetchall()
    db.close()

    return [dict(r) for r in rows]


# ---------- STATS CALCULATION ----------

def stats_from_report(report: dict) -> dict:
    """Calculate stats from an existing report JSON file."""
    fills = report.get("fills", [])
    daily_pnl = report.get("daily_pnl", {})
    total_pnl = daily_pnl.get("total", 0)
    realized = daily_pnl.get("realized", 0)
    fees = daily_pnl.get("fees", 0)
    balance = report.get("total_balance", STARTING_CAPITAL)
    sol_price = report.get("sol_price", 0)

    # Pair BUY/SELL fills to estimate individual round-trip trades
    buys = [f for f in fills if f["side"] == "BUY"]
    sells = [f for f in fills if f["side"] == "SELL"]
    num_roundtrips = min(len(buys), len(sells))

    return {
        "total_fills": report.get("fills_today", len(fills)),
        "estimated_roundtrips": num_roundtrips,
        "total_pnl": total_pnl,
        "realized_pnl": realized,
        "fees": fees,
        "balance": balance,
        "sol_price": sol_price,
        "pnl_pct": (total_pnl / STARTING_CAPITAL) * 100,
        "fills": fills,
    }


def stats_from_db_trades(trades: list[dict], live: dict | None = None) -> dict:
    """
    Calculate stats from trade_log rows, overlaid with authoritative live-status
    when available.

    Semantics (corrected 2026-04-23 after Telegram-report balance bug):
      - `today_pnl`       = sum of today's trades (was being called `total_pnl` —
                            that name was misleading because it wasn't cumulative)
      - `today_fees`      = sum of today's per-trade fees
      - `balance`         = CUMULATIVE account balance (from live-status, not
                            1000 + today_pnl)
      - `cumulative_pnl`  = total_pnl from live-status (realized + unrealized,
                            net of fees + funding)
      - `realized_delta`  = cumulative realized — shows the `gross trade PnL`
                            column separately from fees/funding
      - `cumulative_fees` = lifetime fees paid
      - `cumulative_funding` = lifetime funding cost

    The "scoreboard lies" framing: when fees + funding > realized_delta the
    account is net negative even on winning-trade days. Surfacing both numbers
    in the report keeps the narrative honest.
    """
    today_pnl = sum(t.get("pnl", 0) for t in trades)
    today_fees = sum(t.get("fees", 0) or 0 for t in trades)
    sells = [t for t in trades if "SELL" in t.get("side", "")]
    wins = sum(1 for t in sells if t.get("pnl", 0) > 0)
    last_price = trades[-1].get("price", 0) if trades else 0

    # Live-status overlays (authoritative for CUMULATIVE metrics)
    if live:
        balance = live.get("balance", STARTING_CAPITAL)
        cumulative_pnl = live.get("total_pnl", 0)
        cumulative_unrealized = live.get("unrealized_pnl", 0)
        cumulative_realized = live.get("realized_delta", 0)
        cumulative_fees = live.get("total_fees", 0)
        cumulative_funding = live.get("funding_cost", 0)
        total_trades = live.get("total_trades", 0)
        total_wins = live.get("total_wins", 0)
        total_losses = live.get("total_losses", 0)
        win_rate = live.get("win_rate", 0)
        # Prefer live position's current price for sol_price
        pos = live.get("position", {}) or {}
        if pos.get("current_price"):
            last_price = pos["current_price"]
    else:
        # Fallback (no network): DB-only accounting — MAY UNDERCOUNT
        # because DB doesn't track cumulative funding properly, and today's
        # slice excludes prior days.
        balance = STARTING_CAPITAL + today_pnl  # known-wrong, flagged in output
        cumulative_pnl = today_pnl
        cumulative_unrealized = 0
        cumulative_realized = today_pnl
        cumulative_fees = today_fees
        cumulative_funding = 0
        total_trades = len(trades)
        total_wins = wins
        total_losses = len(sells) - wins
        win_rate = (wins / len(sells) * 100) if sells else 0

    return {
        # Today's slice (unchanged semantics, clearer names)
        "total_fills": len(trades),
        "estimated_roundtrips": len(sells),
        "today_pnl": today_pnl,
        "today_fees": today_fees,
        "today_pnl_pct": (today_pnl / STARTING_CAPITAL) * 100,

        # Backwards-compat keys (so existing format_* functions don't break)
        # but now driven by live data when available:
        "total_pnl": today_pnl,  # preserved for callers; "today_pnl" is preferred
        "realized_pnl": today_pnl,
        "fees": today_fees,
        "pnl_pct": (today_pnl / STARTING_CAPITAL) * 100,

        # CUMULATIVE — these are the authoritative numbers (added 2026-04-23)
        "balance": balance,
        "cumulative_pnl": cumulative_pnl,
        "cumulative_pnl_pct": (cumulative_pnl / STARTING_CAPITAL) * 100,
        "cumulative_unrealized": cumulative_unrealized,
        "cumulative_realized": cumulative_realized,
        "cumulative_fees": cumulative_fees,
        "cumulative_funding": cumulative_funding,
        "carry_cost": cumulative_fees + cumulative_funding,
        "total_trades": total_trades,
        "total_wins": total_wins,
        "total_losses": total_losses,
        "win_rate": win_rate,

        "sol_price": last_price,
        "fills": [],
        "live_source": "live-status" if live else "db-fallback (may undercount)",
    }


# ---------- CHART GENERATION ----------

def generate_chart(stats: dict, target_date: str, output_path: Path):
    """Generate a branded daily P&L chart."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("⚠️  matplotlib not installed. Skipping chart.")
        return None

    fills = stats.get("fills", [])
    if not fills:
        return None

    # Build cumulative P&L from fills (estimate from BUY→SELL pairs)
    BG = "#0d0d1a"
    PURPLE = "#8b5cf6"
    GREEN = "#22c55e"
    RED = "#ef4444"
    TEXT = "#e2e8f0"
    GRID = "#1e1e3a"

    # Plot price over time from fills
    times = []
    prices = []
    for f in fills:
        t = f.get("time", "")
        try:
            dt = datetime.strptime(t, "%Y-%m-%dT%H:%M:%S")
            times.append(dt)
            prices.append(f["price"])
        except (ValueError, KeyError):
            continue

    if len(times) < 2:
        return None

    fig, ax = plt.subplots(figsize=(10, 5))
    fig.patch.set_facecolor(BG)
    ax.set_facecolor(BG)

    # Price line
    ax.plot(times, prices, color=PURPLE, linewidth=2, zorder=3)

    # Mark buys and sells
    buy_t = [times[i] for i, f in enumerate(fills) if f.get("side") == "BUY" and i < len(times)]
    buy_p = [prices[i] for i, f in enumerate(fills) if f.get("side") == "BUY" and i < len(times)]
    sell_t = [times[i] for i, f in enumerate(fills) if f.get("side") == "SELL" and i < len(times)]
    sell_p = [prices[i] for i, f in enumerate(fills) if f.get("side") == "SELL" and i < len(times)]

    ax.scatter(buy_t, buy_p, color=GREEN, marker="^", s=40, zorder=4, label="BUY")
    ax.scatter(sell_t, sell_p, color=RED, marker="v", s=40, zorder=4, label="SELL")

    # Styling
    pnl_color = GREEN if stats["total_pnl"] >= 0 else RED
    ax.set_title(f"iBitLabs — {target_date}  |  P&L: ${stats['total_pnl']:+.2f}",
                 color=TEXT, fontsize=16, fontweight="bold", pad=15)
    ax.set_ylabel("SOL/USD Price", color=TEXT, fontsize=12)
    ax.tick_params(colors=TEXT)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color(GRID)
    ax.spines["bottom"].set_color(GRID)
    ax.grid(True, color=GRID, alpha=0.3)
    ax.legend(facecolor=BG, edgecolor=GRID, labelcolor=TEXT, fontsize=9)

    # Stats bar
    stats_text = (
        f"Fills: {stats['total_fills']}  |  "
        f"Balance: ${stats['balance']:,.2f}  |  "
        f"SOL: ${stats['sol_price']:.2f}"
    )
    ax.text(0.5, -0.12, stats_text, transform=ax.transAxes, ha="center",
            color=TEXT, fontsize=10, alpha=0.8)

    ax.text(0.98, 0.02, "ibitlabs.com", transform=ax.transAxes, ha="right",
            color=PURPLE, fontsize=9, alpha=0.6, fontstyle="italic")

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight", facecolor=BG)
    plt.close()
    return output_path


# ---------- REPORT FORMATTING ----------

def format_telegram(stats: dict, target_date: str) -> str:
    """Telegram MarkdownV2 daily report."""
    pnl_emoji = "🟢" if stats["total_pnl"] >= 0 else "🔴"

    def esc(t):
        for c in ['_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!']:
            t = t.replace(c, f"\\{c}")
        return t

    # Cumulative context (honest scoreboard) — added 2026-04-23 to fix the
    # "Balance: $1,016.92" misstatement. Daily P&L alone lies; carry breaks
    # the narrative so readers see the real account state.
    cum_pnl_s = esc(f"{stats.get('cumulative_pnl', 0):+.2f}")
    cum_pnl_pct_s = esc(f"{stats.get('cumulative_pnl_pct', 0):+.2f}")
    bal_s = esc(f"{stats['balance']:,.2f}")
    cum_emoji = "🟢" if stats.get('cumulative_pnl', 0) >= 0 else "🔴"
    carry_s = esc(f"{stats.get('carry_cost', 0):.2f}")
    realized_s = esc(f"{stats.get('cumulative_realized', 0):+.2f}")

    if stats["total_fills"] == 0:
        # No-trade day — still show cumulative context so readers know the truth
        return (
            f"📊 *iBitLabs Daily Report — {esc(target_date)}*\n\n"
            f"No trades today\\. Bot is running — market didn't trigger entries\\.\n\n"
            f"*Experiment to date:*\n"
            f"{cum_emoji} Balance: ${bal_s} \\({cum_pnl_pct_s}%\\)\n"
            f"Realized: ${realized_s}  \\|  Carry \\(fees \\+ funding\\): \\-${carry_s}\n\n"
            f"🔗 [Live Signals]({SIGNALS_URL})"
        )

    # Day's slice
    pnl_s = esc(f"{stats['today_pnl']:+.2f}")
    pnl_pct_s = esc(f"{stats['today_pnl_pct']:+.2f}")
    fees_s = esc(f"{stats['today_fees']:.2f}")
    sol_s = esc(f"{stats['sol_price']:.2f}")
    trades_today = stats['total_fills']
    wr_s = esc(f"{stats.get('win_rate', 0):.1f}")
    total_trades_s = esc(f"{stats.get('total_trades', 0)}")

    return (
        f"📊 *iBitLabs Daily Report — {esc(target_date)}*\n\n"
        f"*Today*\n"
        f"{pnl_emoji} P&L: ${pnl_s} \\({pnl_pct_s}%\\)  \\|  "
        f"Fills: {trades_today}  \\|  Fees: ${fees_s}\n"
        f"SOL: ${sol_s}\n\n"
        f"*Experiment to date*\n"
        f"{cum_emoji} Balance: ${bal_s} \\({cum_pnl_pct_s}%\\)\n"
        f"Realized: ${realized_s}  \\|  Carry: \\-${carry_s}\n"
        f"{total_trades_s} trades  \\|  WR {wr_s}%\n\n"
        f"_$1,000 real money\\. Fully transparent\\._\n\n"
        f"🔗 [Live Signals]({SIGNALS_URL}) \\| [The Saga]({SAGA_URL})"
    )


def format_twitter(stats: dict, target_date: str) -> str:
    """Twitter post."""
    pnl_sign = "+" if stats["total_pnl"] >= 0 else ""
    emoji = "🟢" if stats["total_pnl"] >= 0 else "🔴"

    return (
        f"📊 Daily Report — {target_date}\n\n"
        f"{emoji} P&L: ${pnl_sign}{stats['total_pnl']:.2f} "
        f"({pnl_sign}{stats['pnl_pct']:.2f}%)\n"
        f"• {stats['total_fills']} fills | Balance: ${stats['balance']:,.2f}\n"
        f"• SOL: ${stats['sol_price']:.2f}\n\n"
        f"$1,000 real money. Every trade recorded.\n"
        f"This is a social experiment.\n\n"
        f"ibitlabs.com\n\n"
        f"#AI #crypto #trading #SOL #buildinpublic"
    )


# ---------- TELEGRAM SEND ----------

def send_telegram(text: str, photo_path: Path = None):
    """Send to Telegram channel."""
    if not TELEGRAM_BOT_TOKEN:
        print("⚠️  TELEGRAM_BOT_TOKEN not set. Skipping.")
        return False

    base = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"
    try:
        if photo_path and photo_path.exists():
            with open(photo_path, "rb") as p:
                resp = requests.post(f"{base}/sendPhoto",
                    data={"chat_id": TELEGRAM_CHANNEL_ID, "caption": text, "parse_mode": "MarkdownV2"},
                    files={"photo": p}, timeout=30)
        else:
            resp = requests.post(f"{base}/sendMessage",
                json={"chat_id": TELEGRAM_CHANNEL_ID, "text": text, "parse_mode": "MarkdownV2"},
                timeout=30)

        if resp.status_code == 200:
            print(f"✅ Telegram sent to {TELEGRAM_CHANNEL_ID}")
        else:
            print(f"❌ Telegram {resp.status_code}: {resp.text[:200]}")
        return resp.status_code == 200
    except Exception as e:
        print(f"❌ Telegram error: {e}")
        return False


# ---------- MAIN ----------

def main():
    parser = argparse.ArgumentParser(description="iBitLabs Daily Report Generator v2")
    parser.add_argument("--date", help="YYYY-MM-DD (default: yesterday)")
    parser.add_argument("--dry-run", action="store_true", help="Don't send to Telegram")
    args = parser.parse_args()

    if args.date:
        target_date = args.date
    else:
        yesterday = datetime.now(timezone.utc) - timedelta(days=1)
        target_date = yesterday.strftime("%Y-%m-%d")

    print(f"📊 Generating daily report for {target_date}...")

    # Fetch live-status FIRST — authoritative for cumulative numbers. This fix
    # (2026-04-23) resolves the Telegram-report balance bug: previous version
    # computed balance = $1000 + today_pnl_only, ignoring prior trades + fees
    # + funding. Live-status is the source of truth.
    live = fetch_live_status()

    # Load data — try report JSON first, then DB
    report = load_report_json(target_date)
    if report:
        print(f"   📄 Found report: reports/{target_date}.json")
        stats = stats_from_report(report)
        # Overlay live-status cumulative fields even when using report JSON
        if live:
            stats["balance"] = live.get("balance", stats["balance"])
            stats["cumulative_pnl"] = live.get("total_pnl", 0)
            stats["cumulative_pnl_pct"] = (live.get("total_pnl", 0) / STARTING_CAPITAL) * 100
            stats["cumulative_realized"] = live.get("realized_delta", 0)
            stats["cumulative_unrealized"] = live.get("unrealized_pnl", 0)
            stats["cumulative_fees"] = live.get("total_fees", 0)
            stats["cumulative_funding"] = live.get("funding_cost", 0)
            stats["carry_cost"] = stats["cumulative_fees"] + stats["cumulative_funding"]
            stats["total_trades"] = live.get("total_trades", 0)
            stats["win_rate"] = live.get("win_rate", 0)
            # "today" fields already computed by stats_from_report
            stats["today_pnl"] = stats.get("total_pnl", 0)
            stats["today_pnl_pct"] = stats.get("pnl_pct", 0)
            stats["today_fees"] = stats.get("fees", 0)
    else:
        print(f"   📄 No report JSON. Checking sol_sniper.db...")
        trades = load_trades_from_db(target_date)
        print(f"   📄 Found {len(trades)} trade_log entries")
        stats = stats_from_db_trades(trades, live=live)

    today_pnl_val = stats.get('today_pnl', stats.get('total_pnl', 0))
    cum_pnl_val = stats.get('cumulative_pnl', 0)
    print(
        f"   Today: P&L ${today_pnl_val:+.2f} | Fills: {stats['total_fills']}  |  "
        f"Cumulative: P&L ${cum_pnl_val:+.2f} | Balance: ${stats['balance']:,.2f}  |  "
        f"source: {stats.get('live_source', 'unknown')}"
    )

    # Generate chart
    chart_path = OUTPUT_DIR / f"chart_{target_date}.png"
    chart = generate_chart(stats, target_date, chart_path)
    if chart:
        print(f"   📈 Chart: {chart_path}")

    # Generate text outputs
    tg_text = format_telegram(stats, target_date)
    tw_text = format_twitter(stats, target_date)

    # Save social media copy
    social_file = OUTPUT_DIR / f"social_{target_date}.txt"
    with open(social_file, "w") as f:
        f.write(f"=== iBitLabs Daily Report — {target_date} ===\n")
        f.write(f"P&L: ${stats['total_pnl']:+.2f} ({stats['pnl_pct']:+.2f}%)\n")
        f.write(f"Fills: {stats['total_fills']} | Balance: ${stats['balance']:,.2f}\n")
        f.write(f"SOL: ${stats['sol_price']:.2f}\n\n")
        f.write("--- TWITTER ---\n")
        f.write(tw_text)
        f.write("\n")
    print(f"   📝 Social copy: {social_file}")

    # Send to Telegram
    if not args.dry_run:
        send_telegram(tg_text, photo_path=chart)
    else:
        print(f"\n--- TELEGRAM PREVIEW ---\n{tg_text}\n")

    # Auto-post to Twitter/X — gated behind TWITTER_ENABLED.
    # Paused 2026-04-22 per operator decision (feedback_social_paused.md).
    # Drafts still saved to social_YYYY-MM-DD.txt for when it's re-enabled.
    if not args.dry_run:
        if not TWITTER_ENABLED:
            print("   🐦 Twitter post skipped (TWITTER_ENABLED=0). Draft saved to social_*.txt.")
        else:
            try:
                from twitter_auto_poster import post_tweet, upload_image
                print("   🐦 Posting to Twitter/X...")
                media_id = upload_image(chart_path) if chart else None
                post_tweet(tw_text, media_id=media_id)
            except Exception as e:
                print(f"   ⚠️  Twitter post skipped: {e}")
    else:
        print(f"\n--- TWITTER PREVIEW ---\n{tw_text}\n")

    print(f"\n✅ Done for {target_date}")


if __name__ == "__main__":
    main()
