#!/bin/zsh
#
# push_claude_public_data.sh — every 15 min cron driver.
#
# Stages ONLY web/public/data/claude_trader.json (the public-facing snapshot
# generated by run_claude_trader.sh after each fire) and pushes it to origin
# main so Cloudflare Pages picks up the latest decisions.
#
# Hard rule: this script never touches other modified files in the working
# tree. It explicitly stages exactly one path. Everything else stays where
# it is.
#
# Companion to ~/Library/LaunchAgents/com.ibitlabs.claude-public-publish.plist
# (15-min cadence). Logs at ~/ibitlabs/logs/claude-public-publish/.

set -u
set -o pipefail

REPO="$HOME/ibitlabs"
DATA_FILE="web/public/data/claude_trader.json"
LOG_DIR="$HOME/ibitlabs/logs/claude-public-publish"
TS="$(date -u +%Y%m%d-%H%M%S)"
LOG="$LOG_DIR/$TS.log"
NTFY_TOPIC="sol-sniper-bonny"

mkdir -p "$LOG_DIR"

ntfy_push() {
  local title="$1" body="$2" priority="${3:-default}" tags="${4:-warning}"
  curl -s -o /dev/null --max-time 5 -X POST \
    -H "Title: $title" \
    -H "Priority: $priority" \
    -H "Tags: $tags" \
    -d "$body" \
    "https://ntfy.sh/$NTFY_TOPIC" 2>&1 || true
}

{
  echo "=== claude-public-publish @ $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
  cd "$REPO" || { echo "FATAL: cannot cd to $REPO"; exit 2; }

  if [[ ! -f "$DATA_FILE" ]]; then
    echo "WARN: $DATA_FILE does not exist yet. Skipping push."
    exit 0
  fi

  # Skip if the data file has not changed (nothing to do).
  if git diff --quiet -- "$DATA_FILE" && \
     ! git ls-files --others --exclude-standard -- "$DATA_FILE" | grep -q .; then
    echo "no diff in $DATA_FILE — nothing to push"
    exit 0
  fi

  # Stage exactly the one file. Never blanket add.
  git add -- "$DATA_FILE"

  # Build commit message from the data file itself for traceability.
  LATEST_INFO=$(python3 - <<'PYEOF'
import json, sys
try:
    d = json.load(open("web/public/data/claude_trader.json", encoding="utf-8"))
    s = d.get("summary", {})
    latest = d.get("latest") or {}
    print(f"n={s.get('decisions_total','?')} "
          f"latest={latest.get('decision','?')} "
          f"price={latest.get('current_price','?')} "
          f"bal={s.get('balance_usd_latest','?')}")
except Exception as e:
    print(f"parse-err: {e}")
PYEOF
)

  git commit -m "data(claude-trader): refresh public snapshot — $LATEST_INFO" \
    || { echo "WARN: commit had nothing to add (race?)"; exit 0; }

  # Push. On failure, ntfy but don't crash the cron.
  if ! git push origin main 2>&1; then
    echo "ERROR: git push failed"
    ntfy_push "[claude-public-publish] push failed" \
      "git push origin main failed at $(date -u +%H:%M:%SZ). Log: $LOG. The data file is committed locally; manual push or next cycle will recover." \
      "default" "warning"
    exit 3
  fi

  echo "pushed: $LATEST_INFO"
} 2>&1 | tee -a "$LOG"
